// Lista representativa de cidades brasileiras (principais capitais, regiões metropolitanas e polos regionais)
export const BRAZILIAN_CITIES = [
  // São Paulo e Grande SP / Interior
  "São Paulo - SP",
  "Guarulhos - SP",
  "Campinas - SP",
  "São Bernardo do Campo - SP",
  "Santo André - SP",
  "Osasco - SP",
  "São José dos Campos - SP",
  "Ribeirão Preto - SP",
  "Sorocaba - SP",
  "Santos - SP",
  "Mauá - SP",
  "São José do Rio Preto - SP",
  "Mogi das Cruzes - SP",
  "Diadema - SP",
  "Jundiaí - SP",
  "Piracicaba - SP",
  "Carapicuíba - SP",
  "Bauru - SP",
  "Itaquaquecetuba - SP",
  "São Vicente - SP",
  "Franca - SP",
  "Praia Grande - SP",
  "Barueri - SP",
  "Taubaté - SP",
  "Suzano - SP",
  "Limeira - SP",
  "Cotia - SP",
  "Taboão da Serra - SP",
  "Embu das Artes - SP",
  "Sumaré - SP",
  "Americana - SP",
  "Araraquara - SP",
  "Jacareí - SP",
  "Hortolândia - SP",
  "Presidente Prudente - SP",
  "Rio Claro - SP",
  "São Carlos - SP",
  "Marília - SP",
  "Indaiatuba - SP",
  "Itu - SP",
  "Bragança Paulista - SP",

  // Rio de Janeiro
  "Rio de Janeiro - RJ",
  "São Gonçalo - RJ",
  "Duque de Caxias - RJ",
  "Nova Iguaçu - RJ",
  "Niterói - RJ",
  "Belford Roxo - RJ",
  "Campos dos Goytacazes - RJ",
  "São João de Meriti - RJ",
  "Petrópolis - RJ",
  "Volta Redonda - RJ",
  "Macaé - RJ",
  "Cabo Frio - RJ",
  "Angra dos Reis - RJ",
  "Nova Friburgo - RJ",
  "Teresópolis - RJ",

  // Minas Gerais
  "Belo Horizonte - MG",
  "Uberlândia - MG",
  "Contagem - MG",
  "Juiz de Fora - MG",
  "Betim - MG",
  "Montes Claros - MG",
  "Ribeirão das Neves - MG",
  "Uberaba - MG",
  "Governador Valadares - MG",
  "Ipatinga - MG",
  "Sete Lagoas - MG",
  "Divinópolis - MG",
  "Poços de Caldas - MG",

  // Paraná
  "Curitiba - PR",
  "Londrina - PR",
  "Maringá - PR",
  "Ponta Grossa - PR",
  "Cascavel - PR",
  "São José dos Pinhais - PR",
  "Foz do Iguaçu - PR",
  "Colombo - PR",
  "Guarapuava - PR",
  "Paranaguá - PR",

  // Rio Grande do Sul
  "Porto Alegre - RS",
  "Caxias do Sul - RS",
  "Canoas - RS",
  "Pelotas - RS",
  "Santa Maria - RS",
  "Gravataí - RS",
  "Viamão - RS",
  "Novo Hamburgo - RS",
  "São Leopoldo - RS",
  "Passo Fundo - RS",

  // Santa Catarina
  "Florianópolis - SC",
  "Joinville - SC",
  "Blumenau - SC",
  "São José - SC",
  "Chapecó - SC",
  "Itajaí - SC",
  "Criciúma - SC",
  "Balneário Camboriú - SC",

  // Centro-Oeste
  "Brasília - DF",
  "Goiânia - GO",
  "Aparecida de Goiânia - GO",
  "Anápolis - GO",
  "Rio Verde - GO",
  "Cuiabá - MT",
  "Várzea Grande - MT",
  "Rondonópolis - MT",
  "Sinop - MT",
  "Campo Grande - MS",
  "Dourados - MS",
  "Três Lagoas - MS",

  // Nordeste
  "Salvador - BA",
  "Feira de Santana - BA",
  "Vitória da Conquista - BA",
  "Camaçari - BA",
  "Fortaleza - CE",
  "Caucaia - CE",
  "Juazeiro do Norte - CE",
  "Sobral - CE",
  "Recife - PE",
  "Jaboatão dos Guararapes - PE",
  "Olinda - PE",
  "Caruaru - PE",
  "Petrolina - PE",
  "São Luís - MA",
  "Imperatriz - MA",
  "Natal - RN",
  "Mossoró - RN",
  "João Pessoa - PB",
  "Campina Grande - PB",
  "Maceió - AL",
  "Arapiraca - AL",
  "Teresina - PI",
  "Parnaíba - PI",
  "Aracaju - SE",
  "Nossa Senhora do Socorro - SE",

  // Norte
  "Manaus - AM",
  "Belém - PA",
  "Ananindeua - PA",
  "Santarém - PA",
  "Porto Velho - RO",
  "Macapá - AP",
  "Rio Branco - AC",
  "Boa Vista - RR",
  "Palmas - TO",

  // Espírito Santo
  "Vitória - ES",
  "Vila Velha - ES",
  "Serra - ES",
  "Cariacica - ES",
  "Cachoeiro de Itapemirim - ES",
  "Linhares - ES",
];
